### PR TITLE
feature(wasm) Add some foreign type hooks for WASM

### PR DESCRIPTION
**Pull request by jeromesimeon**
Signed-off-by: Jerome Simeon <jeromesimeon@me.com>

## Changes

- Add foreign WASM type (WSON)
- Add hook to compiler for compiling EJson foreign data to WSON foreign data

This is work in progress, for review. Still need to add foreign operator mapping.

### CODE REVIEW

**Comment by pkel** [comment]
Cool. I try to recap our last discussion on slack. We have to deal with two different foreign concepts: foreign data and foreign operators. At compile time, we want to translate foreign data to a binary representation (OCaml string). Also foreign operators have to be represented as string. The compiler (`('a, 'b) imp_ejson -> wasm_ast`) will get two new arguments of type `'a -> string` and `'b -> string`.

This PR adds the `'a -> string` argument.

**Review by pkel — APPROVED** [review]

**Comment by pkel** [comment]
I'm wondering whether it makes sense to take a slightly different route. The current signature of the backend is
```ocaml
val imp_ejson_to_wasm_ast : brand_hierarchy -> ('fdata, 'fop) imp_ejson -> Wasm.Ast.module_
val eval : Wasm.Ast.module_ -> char list
  -> (char list * 'fdata ejson) list -> ('fdata ejson) option
```
You propose in this PR
```ocaml
val imp_ejson_to_wasm_ast : brand_hierarchy -> ('fdata -> string) -> ('fdata, 'fop) imp_ejson -> Wasm.Ast.module_
val eval : Wasm.Ast.module_ -> char list
  -> (char list * 'fdata ejson) list -> ('fdata ejson) option
```
I think I could proceed with
```ocaml
val imp_ejson_to_wasm_ast : ('fop -> string) -> brand_hierarchy -> (string, 'fop) imp_ejson -> Wasm.Ast.module_
val eval : Wasm.Ast.module_ -> char list
  -> (string -> 'fop option) -> ('fop -> string ejson list ->  string ejson option)
  -> (char list * string ejson) list -> (string ejson) option
```

**Comment by jeromesimeon** [comment]
> 
> I think I could proceed with
> 
> ```ocaml
> val imp_ejson_to_wasm_ast : ('fop -> string) -> brand_hierarchy -> (string, 'fop) imp_ejson -> Wasm.Ast.module_
> val eval : Wasm.Ast.module_ -> char list
>   -> (string -> 'fop option) -> ('fop -> string ejson list ->  string ejson option)
>   -> (char list * string ejson) list -> (string ejson) option
> ```

@pkel I think I've got the first of those two right now. https://github.com/jeromesimeon/qcert/blob/d609f0479d50ba6be2ff2bea4cf9d86fae7eb79a/compiler/wasm/wasm_backend.ml#L16

I still have to do `eval` ...

**Comment by jeromesimeon** [comment]
hi @pkel, in the `eval` signature below:

> I think I could proceed with
> 
> ```ocaml
> val imp_ejson_to_wasm_ast : ('fop -> string) -> brand_hierarchy -> (string, 'fop) imp_ejson -> Wasm.Ast.module_
> val eval : Wasm.Ast.module_ -> char list
>   -> (string -> 'fop option) -> ('fop -> string ejson list ->  string ejson option)
>   -> (char list * string ejson) list -> (string ejson) option
> ```

the `('fop -> string ejson list ->  string ejson option)` doesn't make sense to me. How can WASM operators work on `ejson` ? Shouldn't they just work on `string` (i.e., foreign types in WASM ?).

Shouldn't it be:

```ocaml
val eval : Wasm.Ast.module_ -> char list
  -> (string -> 'fop option) -> ('fop -> string list ->  string option)
  -> (char list * string ejson) list -> (string ejson) option
```

**Comment by pkel** [comment]
Consider a foreign library `Date` with the following interface.
```ocaml
type t
val parse: string -> t option
val create: float -> t option
val add_seconds: t -> int -> t
val get_month: t -> int
(* ... *)
```
I think values of type `t` should be encoded as [`ejforeign`](https://github.com/querycert/qcert/blob/0f07b1cd6c2ca53330dc0290d5d7a64a542116b4/compiler/core/EJson/Model/EJson.v#L42). From the wasm side, an `ejforeign` will look similar to a JS `ArrayBuffer`.

Arguments and return values of types `string`, `float`, `int`, and `option` should become `ejstring`, `ejfloat`, `ejbigint`, and `ejobject`. If my interpretation is correct, the generic type for foreign operator evaluation is `ejson list -> ejson option`.

**Comment by jeromesimeon** [comment]
> Consider a foreign library `Date` with the following interface.
> 
> ```ocaml
> type t
> val parse: string -> t option
> val create: float -> t option
> val add_seconds: t -> int -> t
> val get_month: t -> int
> (* ... *)
> ```
> 
> I think values of type `t` should be encoded as [`ejforeign`](https://github.com/querycert/qcert/blob/0f07b1cd6c2ca53330dc0290d5d7a64a542116b4/compiler/core/EJson/Model/EJson.v#L42). From the wasm side, an `ejforeign` will look similar to a JS `ArrayBuffer`.
> 
> Arguments and return values of types `string`, `float`, `int`, and `option` should become `ejstring`, `ejfloat`, `ejbigint`, and `ejobject`. If my interpretation is correct, the generic type for foreign operator evaluation is `ejson list -> ejson option`.

But I thought we had a mapping from `ejforeign` to `string` already. Why wouldn't eval work on the right-hand side of that?

**Pull request merged**
