### PR TITLE
Webassembly backend (WIP)

### PR DESCRIPTION
**Pull request by pkel**
This PR adds a Webassembly backend to the QCert compiler framework. The PR is WIP.

We have a discussion thread in the Accord project's slack: https://accord-project.slack.com/archives/C013AS35ZU3

### CODE REVIEW

**Comment by jeromesimeon** [comment]
@pkel Do you know if the OCaml `wasm` package require a special purpose opam repository?

```
File "compiler/dune", line 12, characters 32-36:
12 |  (libraries base64 uri calendar wasm)
```

**Comment by jeromesimeon** [comment]
I think just need to add `wasm` to the CircleCI script here:
https://github.com/querycert/qcert/blob/a3891edc8c9297ec2b126927ef68018fe2142434/.circleci/config.yml#L41

**Comment by pkel** [comment]
> @pkel Do you know if the OCaml `wasm` package require a special purpose opam repository?
> 
> ```
> File "compiler/dune", line 12, characters 32-36:
> 12 |  (libraries base64 uri calendar wasm)
> ```

No, but you need a recent OCaml (>=4.08.0)

https://opam.ocaml.org/packages/wasm/

**Review by jeromesimeon — APPROVED** [review]
Looks great! The only thing right now I can see is to fix the CircleCI to get the CI happy again. We just need to add the `wasm` dependency to the opam installation in the script on this line:
https://github.com/querycert/qcert/blob/a3891edc8c9297ec2b126927ef68018fe2142434/.circleci/config.yml#L41

**Pull request merged**
